---
- name: Install MariaDB
  tags: mariadb
  become: yes
  apt:
    name: mariadb-server
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Install MariaDB
  tags: mariadb
  become: yes
  yum:
    name: mariadb-server
    state: present
  when: ansible_distribution == "CentOS"

